apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: my-urlshrt-svc
  labels:
    app: urlshrt
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: urlshrt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-urlshrt
  labels:
    app: urlshrt
spec:
  replicas: 5
  selector:
    matchLabels:
      app: urlshrt
  template:
    metadata:
      labels:
        app: urlshrt
    spec:
      containers:
        - name: urlshrt
          image: jabacode/url-shortening
          imagePullPolicy: Never
          ports:
            - containerPort: 8080